# Generated by Django 3.0.4 on 2020-03-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher_num_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='num_classes',
        ),
    ]
