# Generated by Django 3.0.4 on 2020-03-15 10:20

from django.db import migrations


def populate_m2m_schools(apps, schema_editor):
    Teacher = apps.get_model('school', 'Teacher')

    for teacher in Teacher.objects.all():
        school_id = teacher.school_id
        teacher.schools.add(school_id)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200315_1017'),
    ]

    operations = [
        migrations.RunPython(populate_m2m_schools)
    ]
